#!/bin/sh -e

# Rebuild initramfs.gz after kernel upgrade to include new kernel's modules.
# https://github.com/Robpol86/robpol86.com/blob/master/docs/_static/initramfs-rebuild.sh
# Save as (chmod +x): /etc/kernel/postinst.d/initramfs-rebuild

# Remove splash from cmdline.
if grep -q '\bsplash\b' /boot/firmware/nobtcmd.txt; then
  sed -i 's/ \?splash \?/ /' /boot/firmware/nobtcmd.txt
fi
if grep -q '\bsplash\b' /boot/firmware/btcmd.txt; then
  sed -i 's/ \?splash \?/ /' /boot/firmware/btcmd.txt
fi
# Exit if not building kernel for this Raspberry Pi's hardware version.
version="$1"
current_version="$(uname -r)"
case "${current_version}" in
  *-v8+)
    case "${version}" in
      *-v8+) ;;
      *) exit 0
    esac
  ;;
  *+)
    case "${version}" in
      *-v8+) exit 0 ;;
    esac
  ;;
esac

# Exit if rebuild cannot be performed or not needed.
[ -x /usr/sbin/mkinitramfs ] || exit 0
[ -f /boot/firmware/initrd.img ] || exit 0
lsinitramfs /boot/firmware/initrd.img | grep -q "/$version$" && exit 0  # Already in initramfs.

# Rebuild.
mkinitramfs -o /boot/firmware/initrd.img "$version"
